# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test
on:
  push:
  pull_request:

jobs:
  build:
    name: Swift on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    steps:
    - uses: k-taro56/setup-swift@main
      with:
        swift-version: 5.9
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: swift build -Xswiftc -strict-concurrency=complete -v
    - name: Run tests
      run: swift test -c release -Xswiftc -strict-concurrency=complete -v